<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

In [3]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

# Aggregation in Window Functions
- COUNT()
- AVG()
- Filtering windows functions

In [6]:
%%sql

SELECT
    customerkey,
    MIN(orderdate) OVER (PARTITION BY customerkey) AS cohort_year
FROM
    sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

        customerkey cohort_year
0                15  2021-03-08
1               180  2018-07-28
2               180  2018-07-28
3               180  2018-07-28
4               185  2019-06-01
...             ...         ...
199868      2099711  2016-08-13
199869      2099711  2016-08-13
199870      2099743  2022-03-17
199871      2099743  2022-03-17
199872      2099743  2022-03-17

[199873 rows x 2 columns]

---
## COUNT

- **COUNT**: Counts the values, `DISTINCT` can be added to get the unique count.
- Syntax:
  ```sql
    SELECT
      COUNT() OVER(
          PARTITION BY partition_expression
      ) AS window_column_alias
      FROM table_name
  ```

-  Group customers by the year of their first purchase, then calculate the total number of customers in each cohort to analyze customer retention and growth trends over time.

#### Total Count of Customers by Cohort

**`COUNT()`, `OVER`, `PARTITION BY`**

1. Get the cohorts by year from the `orderdate` and the `customerkey` in the `sales` table.
    - Use `EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey))` to find the earliest year a customer placed an order.
    - Select `customerkey` to associate each customer with their cohort year.

In [7]:
%%sql

SELECT
    customerkey,
    EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year
FROM
    sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

        customerkey cohort_year
0                15        2021
1               180        2018
2               180        2018
3               180        2018
4               185        2019
...             ...         ...
199868      2099711        2016
199869      2099711        2016
199870      2099743        2022
199871      2099743        2022
199872      2099743        2022

[199873 rows x 2 columns]

2. Add in the purchase year using `EXTRACT`.
    - Use `EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey))` to find the earliest year a customer placed an order.
    - Select `customerkey` to associate each customer with their cohort year.
    - 🔔 Get the `purchase_year` using `EXTRACT(YEAR FROM orderdate) AS purchase_year`

In [8]:
%%sql

SELECT
    customerkey,
    EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year,
    EXTRACT(YEAR FROM orderdate) AS purchase_year
FROM
    sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

        customerkey cohort_year purchase_year
0                15        2021          2021
1               180        2018          2018
2               180        2018          2023
3               180        2018          2023
4               185        2019          2019
...             ...         ...           ...
199868      2099711        2016          2017
199869      2099711        2016          2016
199870      2099743        2022          2022
199871      2099743        2022          2022
199872      2099743        2022          2023

[199873 rows x 3 columns]

3. Get total customers by cohort using window functions.
    - 🔔 First create a CTE to identify each customer's cohort year
        - Use `EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey))` to find the earliest year a customer placed an order.
        - Select `customerkey` to associate each customer with their cohort year.
        - Get the `purchase_year` using `EXTRACT(YEAR FROM orderdate) AS purchase_year`
        - Use `DISTINCT` for the SELECT statement.
    - In the main query:
        - Select the `cohort_year` and `purchase_year`
        - Use `COUNT(customerkey) OVER (PARTITION BY purchase_year, cohort_year)` to count customers in each cohort
        - Add `DISTINCT` to show only one row per cohort year
        - Order by cohort year to show progression

In [15]:
%%sql

WITH yearly_cohort AS (
    SELECT DISTINCT
        customerkey,
        EXTRACT(YEAR FROM (MIN(orderdate) OVER (PARTITION BY customerkey))) AS cohort_year,
        EXTRACT(YEAR FROM orderdate) AS purchase_year
    FROM
        sales
)
SELECT DISTINCT
    cohort_year,
    purchase_year,
    COUNT(customerkey) OVER (PARTITION BY purchase_year, cohort_year) AS num_customers
FROM
    yearly_cohort
ORDER BY
    cohort_year,
    purchase_year;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  num_customers
0         2015          2015           2825
1         2015          2016            126
2         2015          2017            149
3         2015          2018            348
4         2015          2019            388
5         2015          2020            171
6         2015          2021            295
7         2015          2022            600
8         2015          2023            499
9         2015          2024            146
10        2016          2016           3397
11        2016          2017            174
12        2016          2018            374
13        2016          2019            457
14        2016          2020            205
15        2016          2021            336
16        2016          2022            746
17        2016          2023            573
18        2016          2024            183
19        2017          2017           4068
20        2017          2018            473
21        2017          2019            570
22        2017          2020            251
23        2017          2021            450
24        2017          2022            943
25        2017          2023            738
26        2017          2024            246
27        2018          2018           7446
28        2018          2019           1081
29        2018          2020            475
30        2018          2021            779
31        2018          2022           1644
32        2018          2023           1407
33        2018          2024            426
34        2019          2019           7755
35        2019          2020            523
36        2019          2021            873
37        2019          2022           1700
38        2019          2023           1439
39        2019          2024            370
40        2020          2020           3031
41        2020          2021            358
42        2020          2022            694
43        2020          2023            547
44        2020          2024            163
45        2021          2021           4663
46        2021          2022           1051
47        2021          2023            889
48        2021          2024            268
49        2022          2022           9010
50        2022          2023           1764
51        2022          2024            561
52        2023          2023           5890
53        2023          2024            332
54        2024          2024           1402

---
## Average

- `AVG()`: Calculates the average of the values

```sql
  SELECT
    AVG() OVER(
         PARTITION BY partition_expression
    ) AS window_column_alias
    FROM table_name
```
- **Lifetime Value (LTV)**: the total revenue a customer generates for a business over their entire relationship.
- Aggregate total revenue per user and calculate the average lifetime value for each cohort.

#### Average LTV by Cohort

**`AVG()`, `OVER`, `PARTITION BY`**

1. Get the `cohort_year` and the total revenue for each user.  
   - Use `EXTRACT(YEAR FROM MIN(orderdate))` to calculate the cohort year for each customer.  
   - Group by `customerkey` to ensure the revenue and cohort year are calculated per user.  
   - Calculate the total revenue for each customer using `SUM(quantity * netprice * exchangerate)`.  
   - Select `cohort_year`, `customerkey`, and the total revenue (`total_customer_net_revenue`) to display the results.

In [19]:
%%sql

SELECT
    customerkey,
    AVG(quantity * netprice * exchangerate) AS net_revenue,
    COUNT(*) OVER(PARTITION BY customerkey) AS total_orders
FROM
    sales
GROUP BY
    customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey  net_revenue  total_orders
0               15      2217.41             1
1              180       836.74             1
2              185      1395.52             1
3              243       287.67             1
4              387       517.32             1
...            ...          ...           ...
49482      2099619       838.74             1
49483      2099656       800.36             1
49484      2099697        12.73             1
49485      2099711      3004.34             1
49486      2099743       356.03             1

[49487 rows x 3 columns]

2. Create a CTE to calculate the cohort year for each customer and their net revenue and return all results in the main query.  
   - 🔔 Define a CTE `yearly_cohort` to extract the cohort year for each customer.  
        - Use `EXTRACT(YEAR FROM MIN(orderdate))` in the CTE to determine the earliest order year for each customer.
        - Calculate the total revenue for each customer using `SUM(quantity * netprice * exchangerate)`.  
        - Group by `customerkey` in the CTE to assign each customer to a single cohort year.  
   - 🔔 In the main query, use `SELECT * FROM yearly_cohort` to return all the results from the CTE.

In [21]:
%%sql

WITH customer_orders AS (
    SELECT
        customerkey,
        quantity * netprice * exchangerate AS order_value,
        COUNT(*) OVER(PARTITION BY customerkey) AS total_orders
    FROM
        sales
)
SELECT
    customerkey,
    total_orders
FROM
    customer_orders;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

        customerkey  total_orders
0                15             1
1               180             3
2               180             3
3               180             3
4               185             1
...             ...           ...
199868      2099711             2
199869      2099711             2
199870      2099743             3
199871      2099743             3
199872      2099743             3

[199873 rows x 2 columns]

3. Get the average customer LTV along side the average LTV for each cohort.
        - Extract the cohort year using `EXTRACT(YEAR FROM MIN(orderdate))`.  
        - Calculate the total revenue for each customer with `SUM(quantity * netprice * exchangerate)`.  
        - Group by `customerkey` to ensure total revenue and cohort year are assigned to each customer.  
   - In the main query:
        - 🔔 Use `AVG(total_customer_net_revenue) OVER (PARTITION BY cohort_year)` to calculate the average revenue per customer for each cohort.  
        - 🔔 Select `cohort_year`, `customerkey`, `total_customer_net_revenue` (rename this to `customer_ltv`) and the average total revenue for output.  
        - 🔔 Use `ORDER BY cohort_year, customerkey` to sort the results by cohort and customer.

In [26]:
%%sql

WITH yearly_cohort AS (
SELECT
    customerkey,
    EXTRACT(YEAR FROM MIN(orderdate)) AS cohort_year,
    SUM(quantity * netprice * exchangerate) AS customer_ltv
FROM
    sales
GROUP BY
    customerkey
)
SELECT
    *,
    AVG(customer_ltv) OVER (PARTITION BY cohort_year) AS avg_cohort_ltv
FROM
    yearly_cohort
ORDER BY
    cohort_year,
    customerkey;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  customer_ltv  avg_cohort_ltv
0             4376        2015        182.00         5271.59
1             4403        2015       9530.35         5271.59
2             4925        2015       6078.08         5271.59
3             5729        2015        192.16         5271.59
4             6048        2015       1903.89         5271.59
...            ...         ...           ...             ...
49482      2093965        2024        475.22         2037.55
49483      2095129        2024        156.00         2037.55
49484      2095691        2024        326.00         2037.55
49485      2096470        2024        535.78         2037.55
49486      2097541        2024       1143.15         2037.55

[49487 rows x 4 columns]

---
## Filtering Windows Function

- Use `WHERE` to filter rows before aggregation.
- Syntax:
    ```sql
    SELECT
        column_name,
        window_function(column_to_aggregate)
            OVER (PARTITION BY partition_column) AS window_column_alias   
    FROM table_name
    WHERE condition; -- Filters data BEFORE applying window function
    ```

In [32]:
%%sql

WITH cohort AS (
    SELECT
        customerkey,
        EXTRACT(YEAR FROM MIN(orderdate) OVER (PARTITION BY customerkey))AS cohort_year
    FROM
        sales
)
SELECT
    *
FROM
    cohort
WHERE
    cohort_year >= '2020';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

81370 rows affected.

       customerkey cohort_year
0               15        2021
1              406        2021
2              406        2021
3              545        2023
4              545        2023
...            ...         ...
81365      2099697        2022
81366      2099697        2022
81367      2099743        2022
81368      2099743        2022
81369      2099743        2022

[81370 rows x 2 columns]