<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Frame Clause
- **Monthly Revenue Trends:** Calculate the running average monthly revenue and the preceding monthly average net revenue.
- **Mid-Term Revenue Patterns:** Compute rolling 3-month revenue average to smooth monthly fluctuations and reveal purchasing behaviors.  
- **Comparing Monthly Revenues**: Calculates average revenue across all months and compare the last month and the third month revenues.
- `CURRENT ROW`
- `N PRECEDING`
- `N FOLLOWING`
- `UNBOUNDED`
    - `UNBOUNDED PRECEDING`
    - `UNBOUNDED FOLLOWING`

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

---
## ROWS, RANGE, GROUPS

[Postgres Source Documentation on Window Function Calls](https://www.postgresql.org/docs/current/sql-expressions.html#:~:text=%5B%20frame_clause%20%5D)

#### `ROWS`

- Defines window frame based on physical row position
- Counts actual rows before/after current row
- Provides precise control over row inclusion

```sql
<window function> OVER (
    PARTITION BY column
    ORDER BY column
    ROWS start_frame
)

```

```sql
<window function> OVER (
    PARTITION BY column
    ORDER BY column
    ROWS BETWEEN start_frame AND end_frame
)
```

#### `start_frame` & `end_frame`

**Start Frame & End Frame:**
- `CURRENT ROW`: Just the current row (simplest)
- `UNBOUNDED PRECEDING`: All rows from start to current row
- `UNBOUNDED FOLLOWING`: All rows from current to end
- `N PRECEDING`: N rows before current row
- `N FOLLOWING`: N rows after current row


```sql
UNBOUNDED PRECEDING
N PRECEDING
CURRENT ROW
N FOLLOWING
UNBOUNDED FOLLOWING
```

#### `RANGE` & `GROUP`

**RANGE**
- Defines window frame based on logical value ranges rather than physical rows
- Useful for time-series data where you want to group by value ranges (e.g. date ranges)
- Treats rows with equal ORDER BY values as a single group

**GROUPS**
- Groups rows that share the same values in the ORDER BY column
- Useful when you want to treat tied values as a single unit


```sql
<window function> OVER (
    PARTITION BY column
    ORDER BY column
    { RANGE | GROUPS } BETWEEN start_frame AND end_frame
)
```

In [8]:
%%sql

WITH monthly_sales AS (
    SELECT
        TO_CHAR(orderdate, 'YYYY-MM') as month,
        SUM(quantity * netprice * exchangerate) as net_revenue
    FROM
        sales
    WHERE
        EXTRACT(YEAR FROM orderdate) = 2023
    GROUP BY
        month
    ORDER BY
        month
)
SELECT
    month,
    net_revenue,
    AVG(net_revenue) OVER (
      ORDER BY month
    ) AS net_revenue_current
FRom
    monthly_sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           3664431.34
1   2023-02   4465204.57           4064817.96
2   2023-03   2244316.52           3457984.14
3   2023-04   1162796.16           2884187.15
4   2023-05   2943005.99           2895950.92
5   2023-06   2864500.03           2890709.10
6   2023-07   2337639.34           2811699.14
7   2023-08   2623919.79           2788226.72
8   2023-09   2622774.85           2769843.18
9   2023-10   2551322.61           2747991.12
10  2023-11   2700103.38           2743637.69
11  2023-12   2928550.93           2759047.13

---
## CURRENT ROW

- **CURRENT ROW**: Refers to the current row in a window frame during a query execution.
  ```sql
  SELECT
    column_name,
    SUM(column_name) OVER(
        PARTITION BY partition_expression
        ORDER BY order_expression
        ROWS BETWEEN CURRENT ROW AND CURRENT ROW
    ) AS window_column_alias
  FROM table_name;
  ```
> **NOTE:** using `ROWS BETWEEN CURRENT ROW AND CURRENT ROW` is redundant and practically useless in SQL window functions. It essentially means the window consists of just the current row, which is the same as using `SUM(column_name) OVER (...)` without specifying `ROWS`.

In [10]:
%%sql

WITH monthly_sales AS (
    SELECT
        TO_CHAR(orderdate, 'YYYY-MM') as month,
        SUM(quantity * netprice * exchangerate) as net_revenue
    FROM
        sales
    WHERE
        EXTRACT(YEAR FROM orderdate) = 2023
    GROUP BY
        month
    ORDER BY
        month
)
SELECT
    month,
    net_revenue,
    AVG(net_revenue) OVER (
      ORDER BY month
      ROWS CURRENT ROW
    ) AS net_revenue_current
FRom
    monthly_sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           3664431.34
1   2023-02   4465204.57           4465204.57
2   2023-03   2244316.52           2244316.52
3   2023-04   1162796.16           1162796.16
4   2023-05   2943005.99           2943005.99
5   2023-06   2864500.03           2864500.03
6   2023-07   2337639.34           2337639.34
7   2023-08   2623919.79           2623919.79
8   2023-09   2622774.85           2622774.85
9   2023-10   2551322.61           2551322.61
10  2023-11   2700103.38           2700103.38
11  2023-12   2928550.93           2928550.93

---
## PRECEDING

- **N PRECEDING**: Refers to `N` rows before the current row in a window frame.
- Syntax:
  ```sql
  SELECT
    column_name,
    SUM(column_name) OVER(
        PARTITION BY partition_expression
        ORDER BY order_expression
        ROWS BETWEEN N PRECEDING AND CURRENT ROW
    ) AS window_column_alias
  FROM table_name;
  ```
- Enables calculations involving the current row and up to `N` preceding rows, such as moving averages or cumulative sums for a fixed number of rows.

In [13]:
%%sql

WITH monthly_sales AS (
    SELECT
        TO_CHAR(orderdate, 'YYYY-MM') as month,
        SUM(quantity * netprice * exchangerate) as net_revenue
    FROM
        sales
    WHERE
        EXTRACT(YEAR FROM orderdate) = 2023
    GROUP BY
        month
    ORDER BY
        month
)
SELECT
    month,
    net_revenue,
    AVG(net_revenue) OVER (
      ORDER BY month
      ROWS BETWEEN 1 PRECEDING AND CURRENT ROW
    ) AS net_revenue_current
FRom
    monthly_sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           3664431.34
1   2023-02   4465204.57           4064817.96
2   2023-03   2244316.52           3354760.54
3   2023-04   1162796.16           1703556.34
4   2023-05   2943005.99           2052901.08
5   2023-06   2864500.03           2903753.01
6   2023-07   2337639.34           2601069.68
7   2023-08   2623919.79           2480779.57
8   2023-09   2622774.85           2623347.32
9   2023-10   2551322.61           2587048.73
10  2023-11   2700103.38           2625712.99
11  2023-12   2928550.93           2814327.15

## N FOLLOWING

- **N FOLLOWING**: Refers to `N` rows after the current row in a window frame.
  ```sql
  SELECT
    column_name,
    SUM(column_name) OVER(
        PARTITION BY partition_expression
        ORDER BY order_expression
        ROWS BETWEEN CURRENT ROW AND N FOLLOWING
    ) AS window_column_alias
  FROM table_name;
  ```
- Useful for calculating aggregations involving the current row and a specified number of subsequent rows, such as projecting future totals or averages.

In [14]:
%%sql

WITH monthly_sales AS (
    SELECT
        TO_CHAR(orderdate, 'YYYY-MM') as month,
        SUM(quantity * netprice * exchangerate) as net_revenue
    FROM
        sales
    WHERE
        EXTRACT(YEAR FROM orderdate) = 2023
    GROUP BY
        month
    ORDER BY
        month
)
SELECT
    month,
    net_revenue,
    AVG(net_revenue) OVER (
      ORDER BY month
      ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING
    ) AS net_revenue_current
FRom
    monthly_sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

      month  net_revenue  net_revenue_current
0   2023-01   3664431.34           4064817.96
1   2023-02   4465204.57           3457984.14
2   2023-03   2244316.52           2624105.75
3   2023-04   1162796.16           2116706.22
4   2023-05   2943005.99           2323434.06
5   2023-06   2864500.03           2715048.45
6   2023-07   2337639.34           2608686.39
7   2023-08   2623919.79           2528111.33
8   2023-09   2622774.85           2599339.08
9   2023-10   2551322.61           2624733.61
10  2023-11   2700103.38           2726658.97
11  2023-12   2928550.93           2814327.15

## UNBOUNDED
- **UNBOUNDED PRECEDING**: Refers to the first row of the partition or dataset in a window frame.
- Syntax:
  ```sql
  SELECT
    column_name,
    SUM(column_name) OVER(
        PARTITION BY partition_expression
        ORDER BY order_expression
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS window_column_alias
  FROM table_name;
  ```
- Commonly used for cumulative calculations starting from the beginning of a partition, such as running totals or cumulative averages.
- **UNBOUNDED FOLLOWING**: Refers to the last row of the partition or dataset in a window frame.
- Syntax:
  ```sql
  SELECT
    column_name,
    SUM(column_name) OVER(
        PARTITION BY partition_expression
        ORDER BY order_expression
        ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING
    ) AS window_column_alias
  FROM table_name;
  ```
- Often used to aggregate values from the current row to the end of the partition, such as totals or counts of future data.

In [18]:
%%sql

WITH monthly_sales AS (
    SELECT
        TO_CHAR(orderdate, 'YYYY-MM') as month,
        SUM(quantity * netprice * exchangerate) as net_revenue
    FROM
        sales
    WHERE
        EXTRACT(YEAR FROM orderdate) = 2023
    GROUP BY
        month
    ORDER BY
        month
)
SELECT
    month,
    net_revenue,
    AVG(net_revenue) OVER (
      ORDER BY month
      ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
    ) AS net_revenue_all,
    AVG(net_revenue) OVER (
      ORDER BY month
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS net_revenue_preceding,
    AVG(net_revenue) OVER (
      ORDER BY month
      ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING
    ) AS net_revenue_following
FRom
    monthly_sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,net_revenue_all,net_revenue_preceding,net_revenue_following
0,2023-01,3664431.34,2759047.13,3664431.34,2759047.13
1,2023-02,4465204.57,2759047.13,4064817.96,2676739.47
2,2023-03,2244316.52,2759047.13,3457984.14,2497892.96
3,2023-04,1162796.16,2759047.13,2884187.15,2526068.12
4,2023-05,2943005.99,2759047.13,2895950.92,2696477.11
5,2023-06,2864500.03,2759047.13,2890709.10,2661258.70
6,2023-07,2337639.34,2759047.13,2811699.14,2627385.15
7,2023-08,2623919.79,2759047.13,2788226.72,2685334.31
8,2023-09,2622774.85,2759047.13,2769843.18,2700687.94
9,2023-10,2551322.61,2759047.13,2747991.12,2726658.97
10,2023-11,2700103.38,2759047.13,2743637.69,2814327.15
11,2023-12,2928550.93,2759047.13,2759047.13,2928550.93